Function methods based on type

In [5]:
methods(cos)
methods(sum)

# 14 methods for generic function "sum":
[1] sum(f::Union{Function, Type}, x::SparseArrays.AbstractSparseVector) in SparseArrays at /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsevector.jl:1376
[2] sum(x::SparseArrays.AbstractSparseVector) in SparseArrays at /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsevector.jl:1378
[3] sum(x::Tuple{Any, Vararg{Any}}) in Base at tuple.jl:493
[4] sum(r::StepRangeLen{<:Any, <:Base.TwicePrecision, <:Base.TwicePrecision}) in Base at twiceprecision.jl:592
[5] sum(r::StepRangeLen) in Base at twiceprecision.jl:577
[6] sum(r::AbstractRange{<:Real}) in Base at range.jl:1312
[7] sum(arr::Union{Tuple{BigInt, Vararg{BigInt}}, AbstractArray{BigInt}}) in Base.GMP at gmp.jl:636
[8] sum(a::AbstractArray{Bool}; kw...) in Base at reduce.jl:533
[9] sum(arr::AbstractArray{BigFloat}) in Base.MPFR at mpfr.jl:730
[10] sum(a::AbstractArray; dims, kw...) in Base at reducedim.jl:889
[11] sum(a; kw...) in Base at reduce.jl:532
[12] sum(f, x::SparseArrays.AbstractSparseVector) in SparseArrays at /opt/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsevector.jl:1377
[13] sum(f, a::AbstractArray; dims, kw...) in Base at reducedim.jl:890
[14] sum(f, a; kw...) in Base at reduce.jl:503

In [32]:
a = 1
b = '1'
print(a, b)
typeof(a), typeof(b), eltype(a), sizeof(a), sizeof(b)

11

(Int64, Char, Int64, 8, 4)

In [33]:
varinfo()

| name |    size | summary |
|:---- | -------:|:------- |
| Base |         | Module  |
| Core |         | Module  |
| Main |         | Module  |
| a    | 8 bytes | Int64   |
| b    | 4 bytes | Char    |


In [39]:
#\alpha+tab
α = 1

1

In [47]:
ℵ = 3
☎ = 1
ℵ+☎

4

In [56]:
pi, π, ℯ ,typeof(ℯ), typeof(pi)

(π, π, ℯ, Irrational{:ℯ}, Irrational{:π})

In [67]:
a = 2 // 8
b = 3 // 7
c = a + b
d = 1 // 0
c, numerator(c), denominator(c), a, d ,float(c), rationalize(float(c))

(19//28, 19, 28, 1//4, 1//0, 0.6785714285714286, 19//28)

In [80]:
a = 3
b = 0x3
c = 0b11
d = 3.0
e = 4 + 3im
f = complex(3, 4)
g = "hi"
a, b, c, d, e, f, g, bitstring(a)

(3, 0x03, 0x03, 3.0, 4 + 3im, 3 + 4im, "hi", "0000000000000000000000000000000000000000000000000000000000000011")

In [83]:
convert(Float32, a), convert(Int16, d)

(3.0f0, 3)

In [95]:
a = 5.6
round(a), ceil(a), floor(a), trunc(a), clamp(a, 5.1, 5.2)

(6.0, 6.0, 5.0, 5.0, 5.2)

In [103]:
a = 5.6; b = 4.8
min(a, b), max(a, b), minmax(a, b)

(4.8, 5.6, (4.8, 5.6))

In [105]:
c = 1.1
+(a, b, c)

11.499999999999998

In [110]:
a = 5
7*a, 7a

(35, 35)

arrays

In [121]:
a = Array{Float64}(undef, 2,2)

2×2 Matrix{Float64}:
 6.94335e-310  6.94341e-310
 6.94335e-310  6.94335e-310

In [119]:
a = ["hi" 2;
    3.2 false]

2×2 Matrix{Any}:
  "hi"      2
 3.2    false

In [122]:
a = Array{Any}(undef, 2, 2, 2)

2×2×2 Array{Any, 3}:
[:, :, 1] =
 #undef  #undef
 #undef  #undef

[:, :, 2] =
 #undef  #undef
 #undef  #undef

In [125]:
ndims(a), size(a), length(a), axes(a)

(3, (2, 2, 2), 8, (Base.OneTo(2), Base.OneTo(2), Base.OneTo(2)))

In [126]:
b = similar(a,Int)

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 140536403740112  140536221927616
 140536439259144  140536382927632

[:, :, 2] =
 140536221927616  140536439259144
 140536403742320  140536439259144

In [133]:
a = ["hi" 1 2 3]
b = a
c = copy(a)
print(a, b)
a[1,1] = ["bye"]
a, b, c

Any["hi" 1 2 3]Any["hi" 1 2 3]

(Any[["bye"] 1 2 3], Any[["bye"] 1 2 3], Any["hi" 1 2 3])

vectors

In [135]:
a = [1, 2, 3]; a = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [143]:
b = [1 2 3]; c = [1 2 3]'
b == c, b == c'

(false, true)

In [152]:
a = collect(2:1:4)
a

3-element Vector{Int64}:
 2
 3
 4

In [159]:
a = range(1, 5, length=2)

1.0:4.0:5.0

In [160]:
collect(a)

2-element Vector{Float64}:
 1.0
 5.0

In [180]:
a = collect(x for x in 1:10 if isodd(x))
b = collect(x for x in 1:10 if iseven(x))
c = [x for x in 1:10 if iseven(x)]
a,b,c, show(a), a[end] ,a[end-1], sort(a)

[1, 3, 5, 7, 9]

([1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [2, 4, 6, 8, 10], nothing, 9, 7, [1, 3, 5, 7, 9])

In [183]:
2 in b, 2 in a, in(2, a)

(true, false, false)

In [188]:
sort(a), popfirst!(a), a   #inplace

([5, 7, 9], 5, [7, 9])

Matrices

In [25]:
a = [1 2; 3 4]
b = [1 2]
broadcast(+,a , b)

2×2 Matrix{Int64}:
 2  4
 4  6

In [26]:
using SparseArrays 

In [30]:
a = spzeros(100,100);
s = sparse(a);

In [32]:
a = Matrix(s);

In [34]:
findnz(s)

(Int64[], Int64[], Float64[])

charecters

In [38]:
Int32('a')

97

In [42]:
Char(97)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

string

In [60]:
a = "i am am"
a[1] ,a[end], typeof(a), a[end-1]

('i', 'm', String, 'a')

IO

In [64]:
a = 1
print(a)
println(a)  #\n
print(a)

11
1

In [68]:
printstyled("a",color=:yellow)

a

In [69]:
a = readline()

stdin> \f


"\\f"

In [86]:
f = open("README.md", "r")
data = read(f, ',')
data

LoadError: MethodError: no method matching read(::IOStream, ::Char)
Closest candidates are:
  read(::AbstractString, ::Any...) at /opt/julia-1.7.2/share/julia/base/io.jl:434
  read(::IOStream) at /opt/julia-1.7.2/share/julia/base/iostream.jl:518
  read(::IO, ::Type{String}) at /opt/julia-1.7.2/share/julia/base/io.jl:969
  ...